# 텐서

## 1. 텐서 생성하기

### 1) 텐서 다뤄보기

In [ ]:
import torch

torch.__version__

'2.6.0+cu124'

In [ ]:
# 길이가 2인 텐서 생성하기

a = torch.tensor([1, 2])
a

tensor([1, 2])

In [ ]:
# shape = size (텐서의 shape), dim (텐서의 차원)
a.shape, a.size(), a.dim()

(torch.Size([2]), torch.Size([2]), 1)

In [ ]:
# 텐서 생성 위치 지정
# cpu , gpu 중 택1

# default는 cpu, gpu로 연산하고 싶다면 'cuda' 입력
print(torch.tensor([[1,2],[3,4]], device="cuda"))

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [ ]:
# 데이터타입(dtype), 학습여부(requires_grad)
print(torch.tensor([1, 2, 3], dtype=torch.float32,
                   device='cpu', requires_grad=True))

tensor([1., 2., 3.], requires_grad=True)


In [ ]:
# 텐서 생성
tensor1 = torch.tensor([1, 2, 3])
print(tensor1)

tensor([1, 2, 3])


In [ ]:
# 파이토치 텐서를 넘파이 ndarray로 변환
ndarray1 = tensor1.numpy()
ndarray1

array([1, 2, 3])

In [ ]:
# ndarray를 텐서로 변환
tensor2 = torch.from_numpy(ndarray1)
tensor2

tensor([1, 2, 3])

텐서플로우에서는 그냥 array로 학습했었는데?
- tensorflow : ndarray를 자동으로 tensor로 변환하여 학습 진행
- pytorch : 자동으로 안해주므로, 직접 tensor로 변환해줘야 한다.

cuda로 세팅된 텐서를 numpy로 변환하기
- 바로 변환 X   
1) cpu로 이동  
2) numpy 변환

In [ ]:
# 텐서 생성
tensor1 = torch.tensor([1, 2, 3], device='cuda')
print(tensor1)

tensor([1, 2, 3], device='cuda:0')


In [ ]:
# 텐서를 넘파이로
ndarray1 = tensor1.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# 텐서 생성
tensor1 = torch.tensor([1, 2, 3],device='cuda')
print(tensor1)

tensor([1, 2, 3], device='cuda:0')


In [ ]:
# 텐서 cpu로 이동
tensor1 = tensor1.cpu()

# 텐서를 넘파이로
ndarray1 = tensor1.numpy()
print(ndarray1)

[1 2 3]


cpu에 있는 텐서를 gpu로 이동하기

In [ ]:
# cuda로 변경
tensor1 = torch.tensor([1, 2, 3])
tensor1.cuda()

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor1 = tensor1.to('cpu')
tensor1

tensor([1, 2, 3])

In [ ]:
tensor1 = tensor1.to('cuda')
tensor1

tensor([1, 2, 3], device='cuda:0')

# < 정리 >
- cpu -> gpu : .cuda() 혹은 .to('cuda')
- gpu -> cpu : .cpu() 혹은 .to('cpu')  
단, .to()를 쓰면, 더 상세 설정이 가능하다. 예를 들어, dtype을 함께 지정하거나, 멀티 gpu를 사용시, gpu 의 인덱스를 설정할 수 있다.

### 문제
1. 임의의 텐서 하나를 cpu에 선언하시고, gpu로 옮겨보세요.
2. 임의의 텐서 하나를 cpu에 선언하시고, ndarray로 바꿔보세요.
3. 임의의 텐서 하나를 gpu에 선언하시고, cpu로 옮겨보세요.
4. 임의의 텐서 하나를 gpu에 선언하시고, ndarray로 바꿔보세요.


In [ ]:
import torch

torch.__version__

'2.6.0+cu124'

In [ ]:
tensor1 = torch.tensor([3, 4, 5], device='cpu')
tensor1 = tensor1.to('cuda')
print(tensor1)

tensor([3, 4, 5], device='cuda:0')


In [ ]:
tensor2 = torch.tensor([2, 1], device='cpu')
ndarray = tensor2.numpy()
ndarray

array([2, 1])

In [ ]:
#임의의 텐서 하나를 gpu에 선언하시고, cpu로 옮겨보세요.
tensor3 = torch.tensor([3, 3], device='cuda')
tensor3 = tensor3.to('cpu')
tensor3

tensor([3, 3])

In [ ]:
#임의의 텐서 하나를 gpu에 선언하시고, ndarray로 바꿔보세요.
tensor4 = torch.tensor([4, 5], device='cuda')
tensor4 = tensor4.to('cpu')
ndarray = tensor4.numpy()
ndarray

array([4, 5])

## 2. 텐서의 차원 조작하기

### 1) 텐서(Tensor)의 인덱스를 조작하는 방법!

In [ ]:
import torch

# 1차원 텐서 생성
tensor = torch.tensor([1, 2, 3, 4, 5])


# 첫 번째 원소에 접근
print(tensor[0])

 # 마지막 원소에 접근
print(tensor[-1])

tensor(1)
tensor(5)


In [ ]:
# 2차원 텐서 생성
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 텐서 형태 보기
print(tensor)

  # 첫 번째 행, 첫 번째 열의 원소에 접근
print(tensor[0, 0])

# 두 번째 행, 세 번째 열의 원소에 접근
print(tensor[1, 2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(1)
tensor(6)


In [ ]:
# 2차원 텐서 생성
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 텐서 형태 보기
print(tensor)

 # 두 번째 행의 모든 원소에 접근
print(tensor[1, :])

 # 첫 번째 행의 첫 번째부터 두 번째 원소에 접근
print(tensor[0, :2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor([1, 2])


In [ ]:
# 2차원 텐서 생성
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(tensor[[0, 1], [0, 1]]) # 1 : (0,0) / 5 : (1,1)

# 2, 6
print(tensor[[0, 1], [1, 2]])

# 3, 5, 7
print(tensor[[0, 1, 2], [2, 1, 0]])

# [[x1, x2, x3], [y1, y2, y3]] => (x1, y1), (x2, y2), (x3, y3)

In [ ]:
# 2차원 텐서 생성
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 텐서 형태 보기
print(tensor)
print(tensor.shape)

 # 두 번째 열의 모든 원소에 접근
print(tensor[:, 1])
print(tensor[:, 1].shape)

 # 첫 번째 열의 첫 번째부터 두 번째 원소에 접근
print(tensor[0:2, 0])
print(tensor[0:2, 0].shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
tensor([2, 5, 8])
torch.Size([3])
tensor([1, 4])
torch.Size([2])


#### 문제
슬라이싱을 반드시 사용하여 아래 텐서에서 문제별로 지정하는 원소만 지칭해봅시다.

In [ ]:
# 2차원 텐서 생성
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# 문제1 : 3, 6, 9
print(tensor[:, 2])
# 문제2 : 7, 8, 9
print(tensor[2, :])
# 문제3 : 2, 5
print(tensor[1:, 2])
# 문제4 : 6, 9
print(tensor[::2, 0])
# 문제5 : 1, 7


tensor([3, 6, 9])
tensor([7, 8, 9])
tensor([6, 9])
tensor([1, 7])


In [ ]:
# @title 정답
# 2차원 텐서 생성
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 문제1 : 3, 6, 9
print(tensor[:, 2])

# 문제2 : 7, 8, 9
print(tensor[2, :])

# 문제3 : 2, 5
print(tensor[:2, 1])

# 문제4 : 6, 9
print(tensor[1:, 2])

# 문제5 : 1, 7
print(tensor[::2, 0])

tensor([3, 6, 9])
tensor([7, 8, 9])
tensor([2, 5])
tensor([6, 9])
tensor([1, 7])


### 2) 텐서(Tensor)의 차원을 조작하는 방법!

#### (1) Reshape, View
둘다 reshape하는 기능인데, view를 권장한다. (안정성, 효율성)

In [ ]:
import torch

# 원래 1차원 텐서 생성
tensor = torch.arange(6)  # tensor: [0, 1, 2, 3, 4, 5]
print("원래의 tensor :",tensor)
print("")

# reshape 함수를 사용하여 텐서의 형태 변경
reshaped_tensor = torch.reshape(tensor, (2, 3)) # 2행 3열
reshaped_tensor = tensor.reshape(2, 3) # 2행 3열
print("reshape 함수 사용 :", reshaped_tensor)
print("")

# view 함수를 사용하여 텐서의 형태 변경
viewed_tensor = tensor.view(2, 3)
print("view 함수 사용 :", viewed_tensor )

view 가 효율적이지만, 불가능한 경우가 있다.
- tensor가 contiguous 하지 않을 때
- contiguous한 tensor만 view가 가능하다.
- non-contiguous한 tensor는?
1. reshape 하거나
2. contiguous하게 바꾸고, view하거나

In [ ]:
# 원래 1차원 텐서 생성
tensor = torch.arange(6)  # tensor: [0, 1, 2, 3, 4, 5]
print("원래의 tensor :",tensor)
print("")

# view 함수를 사용하여 텐서의 형태 변경
viewed_tensor = tensor.view((2, 4))
print("view 함수 사용 :", viewed_tensor)

In [ ]:
# 원래 1차원 텐서 생성
tensor = torch.arange(6)  # tensor: [0, 1, 2, 3, 4, 5]
print("원래의 tensor :",tensor)
print("")

# 2차원 텐서로 변형. 열의 수 자동 계산
viewed_tensor = tensor.view((2, -1)) # 2행 X 나머지 맞춰서 열
print("2행 x열 :", viewed_tensor)
print("")

# 2차원 텐서로 변형. 행의 수 자동 계산
viewed_tensor = tensor.view((-1, 2))
print("x행 2열 :", viewed_tensor)

원래의 tensor : tensor([0, 1, 2, 3, 4, 5])

2행 x열 : tensor([[0, 1, 2],
        [3, 4, 5]])

x행 2열 : tensor([[0, 1],
        [2, 3],
        [4, 5]])


#### (2) Squeeze, Unsqueeze
- squeeze : 값이 1인 차원의 인덱스를 지정하여, 해당 차원을 제거할 수 있다. (차원 중에 값이 1인 차원을 제거할 때 사용)
- unsqueeze : 지정한 인덱스에 값을 1로 차원을 추가할 수 있다.
(값이 1인 차원을 추가할 때 사용)

오해금지 : 값을 제거하는 게 아니라, 차원 자체를 제거하는 것

In [ ]:
torch.arange(9).shape

torch.Size([9])

In [ ]:
# 크기가 (1, 3, 3)인 텐서
tensor = torch.arange(9).view((1,9))
print(tensor) # (1, 9)
print(tensor.shape) # (1, 9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])
torch.Size([1, 9])


In [ ]:
# 첫 번째 차원 제거
print(tensor.squeeze(0)) # 9,
print(tensor.squeeze(0).shape) # 9,

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([9])


In [ ]:
# 크기가 (1, 3, 3)인 텐서
tensor = torch.arange(9)
print(tensor)
print(tensor.shape)
print()

# 첫 번째 차원 추가
print(tensor.unsqueeze(0))
print(tensor.unsqueeze(0).shape)
print()

# 두 번째 차원 추가
print(tensor.unsqueeze(-1))
print(tensor.unsqueeze(-1).shape)

#### 직접 풀어봅시다
문제1) 아래 (3, 1, 4) 모양의 텐서 'x'가 있습니다. 'squeeze' 및 'unsqueeze'를 사용하여 필요한 작업을 수행하여 모양 (3, 4)의 텐서로 다시 만드세요.

In [ ]:
import torch

x = torch.randn(3, 4)
x

tensor([[ 0.2170, -0.0312, -1.3511, -1.2114],
        [-2.7790, -0.3477, -1.9250,  0.6945],
        [ 1.6382, -0.8289, -1.0752,  0.0542]])

In [ ]:
# @title 정답

x_sq = x.squeeze(1)
print(x_sq.shape)
print(x_sq)

문제2) 다시 (1, 3, 4) 모양의 텐서로 만드세요

In [ ]:
# @title 정답
x_un = x_sq.unsqueeze(0)
print(x_un)
print(x_un.shape)

#### (3) Transpose, cat, stack

In [ ]:
import torch

In [ ]:
# transpose

# 원래 텐서 생성
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:")
print(tensor)
print(tensor.shape)
print("")

# transpose 함수를 사용하여 첫 번째 차원과 두 번째 차원의 위치를 바꿈
transposed_tensor = torch.transpose(tensor, 0, 1)
transposed_tensor = tensor.transpose(0, 1)
transposed_tensor = tensor.T
print("Transposed Tensor:")
print(transposed_tensor)
print(transposed_tensor.shape)

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])

Transposed Tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


In [ ]:
# transpose는 데이터를 따로 복사하지 않는 연산임.
tensor[0, 0] = 100 # 원본 수정
print(tensor)

In [ ]:
# transpose는 원본을 참조하는 메타데이터 저장하는 연산임.
# 대신 transpose가 되도록 원소의 순서를 바꾸는 연산임.
transposed_tensor # transpose도 같이 수정

In [ ]:
# 텐서의 contiguous
# 원소의 순서를 바꾼다는게 contiguous가 깨진다는 의미임
# non-contiguous : 메모리에 저장된 원소의 순서와 가져오는 순서가 다르다.
print(tensor.is_contiguous())
print(transposed_tensor.is_contiguous())

In [ ]:
tensor.view(6)

In [ ]:
transposed_tensor.view(6)

In [ ]:
# 대안1 : reshape 사용
transposed_tensor.reshape(6)

In [ ]:
# 대안2 : contiguous하게 바꾼후, view()
print(transposed_tensor.contiguous().view(6))

In [ ]:
# 원래 3차원 텐서 생성
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]],
                        [[7, 8, 9], [10, 11, 12]]])
print("Original Tensor:")
print(tensor)
print(tensor.shape)
print("")

# transpose 함수를 사용하여 첫 번째 차원과 세 번째 차원의 위치를 바꿈
transposed_tensor = torch.transpose(tensor, 0, 2)
print("Transposed Tensor:")
print(transposed_tensor)
print(transposed_tensor.shape)

Original Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])

Transposed Tensor:
tensor([[[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]],

        [[ 3,  9],
         [ 6, 12]]])
torch.Size([3, 2, 2])


In [ ]:
# cat : concat (병합) - 두 개 이상의 텐서를 하나의 텐서로

# 원래 텐서 생성
tensor1 = torch.tensor([[1, 2, 3],[4, 5, 6]])
tensor2 = torch.tensor([[7, 8, 9],[10,11,12],[13,14,15]])
print("Original Tensors:")
print(tensor1)
print("tensor1 size :", tensor1.shape)
print(tensor2)
print("tensor2 size :", tensor2.shape)
print("")

# cat 함수를 사용하여 두 텐서를 연결
cat_tensor = torch.cat((tensor1, tensor2), dim=0)
print("Concatenated Tensor:")
print(cat_tensor)
print("cat_tensor size :", cat_tensor.shape)

병합에서 핵심은 병합하는 방향(차원)을 결정하는 것
- dim 값 결정하는 법  
    - 1.결과 텐서의 차원을 생각하기
    - 2.원래 텐서들의 차원을 생각하기
    - 3.어느차원이 다른지 확인하기
    - 4.다른 그 차원 = dim값

In [ ]:
# 원래 텐서 생성
tensor1 = torch.tensor([[1, 2, 3],[4, 5, 6]])
tensor2 = torch.tensor([[7, 8, 9],[10,11,12],[13,14,15]])
print("Original Tensors:")
print(tensor1)
print("tensor1 size :", tensor1.shape)
print(tensor2)
print("tensor2 size :", tensor2.shape)
print("")

# cat 함수를 사용하여 두 텐서를 연결
cat_tensor = torch.stack((tensor1, tensor2), dim=0)
print("Concatenated Tensor:")
print(cat_tensor)
print("cat_tensor size :", cat_tensor.shape)

Original Tensors:
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor1 size : torch.Size([2, 3])
tensor([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
tensor2 size : torch.Size([3, 3])



RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [3, 3] at entry 1

In [ ]:
# 원래 텐서 생성
tensor1 = torch.tensor([[1, 2, 3],[4, 5, 6]])
tensor2 = torch.tensor([[7, 8, 9],[10,11,12]])
print("Original Tensors:")
print(tensor1)
print("tensor1 size :", tensor1.shape)
print(tensor2)
print("tensor2 size :", tensor2.shape)
print("")

# stack 함수를 사용하여 두 텐서를 연결
stack_tensor = torch.stack((tensor1, tensor2), dim=0)
print("stack tensor:")
print(stack_tensor)
print("stack_tensor size :", stack_tensor.shape)

Original Tensors:
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor1 size : torch.Size([2, 3])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor2 size : torch.Size([2, 3])

stack tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
stack_tensor size : torch.Size([2, 2, 3])


In [ ]:
# stacked tensor에서 원하는 원소 지정하기
# 원소 8 지정(인덱싱)해보기


### 문제:
1. (2, 3) 모양의 텐서 'A'가 있습니다. 텐서를 전치하고 결과를 'A_transposed'에 저장합니다.
  
  
2. 각각 모양이 (4, 3)과 (4, 3)인 두 개의 텐서 'B'와 'C'가 있습니다. 지정된 차원을 따라 연결하여 새 텐서 'D'를 만듭니다.  
  

3. 모양이 (3,)과 (3,)인 두 개의 텐서 'E'와 'F'가 있습니다. 이를 새로운 차원에 따라 쌓아 2D 텐서 'G'를 만듭니다.

In [ ]:
# 1
A = torch.randn(2, 3)
A_transposed = torch.transpose(tensor, 0, 1)
print(A_transposed)
# 2
B = torch.randn(4, 3)
C = torch.randn(4, 3)
D = torch.cat((B, C), dim=0)
print(D)
# 3
E = torch.randn(3)
F = torch.randn(3)
G = torch.stack((E, F), dim=0)
print(G)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
tensor([[ 0.2169, -0.3352, -0.8561],
        [-2.2154, -0.4099,  0.6690],
        [-0.3377, -0.3262,  0.0429],
        [-1.0447,  0.7779, -1.5012],
        [ 0.5964,  3.2162, -0.3219],
        [-0.5531, -0.1611,  1.4881],
        [-1.7697, -0.0383,  0.4190],
        [-1.3965, -1.2618, -0.3715]])
tensor([[-0.2360, -1.0909,  0.8060],
        [-0.0803,  0.8401,  0.5420]])


In [ ]:
# @title 정답
# 1
A = torch.randn(2, 3)
A_t1 = torch.transpose(A, 0, 1)
A_t2 = A.transpose(0, 1)
A_t3 = A.T
print('전치행렬 : ')
print(A_t1)
print(A_t2)
print(A_t3)
print('-'*30)
print()
# 2
B = torch.randn(4, 3)
C = torch.randn(4, 3)
cat0 = torch.cat((B, C), dim=0)
cat1 = torch.cat((B, C), dim=1)
print('concat by dim 0')
print(cat0)
print('concat by dim 1')
print(cat1)
print('-'*30)
print()

# 3
E = torch.randn(3)
F = torch.randn(3)
print(E)
print(F)
stk = torch.stack((E, F), dim=0)
print(stk)
print(stk.shape)

전치행렬 : 
tensor([[0.3547, 0.0202],
        [1.2950, 0.5215],
        [0.6344, 0.6946]])
tensor([[0.3547, 0.0202],
        [1.2950, 0.5215],
        [0.6344, 0.6946]])
tensor([[0.3547, 0.0202],
        [1.2950, 0.5215],
        [0.6344, 0.6946]])
------------------------------

concat by dim 0
tensor([[ 0.2072,  0.1783,  2.5353],
        [ 0.4109,  0.8513,  0.5078],
        [-0.2156, -0.3077, -1.5949],
        [ 0.6170,  0.4535,  0.5172],
        [-0.7830,  0.3327,  0.1154],
        [ 0.4859, -1.3900,  0.1925],
        [ 1.0177, -0.5163,  1.4049],
        [-0.0322,  0.7324, -1.1831]])
concat by dim 1
tensor([[ 0.2072,  0.1783,  2.5353, -0.7830,  0.3327,  0.1154],
        [ 0.4109,  0.8513,  0.5078,  0.4859, -1.3900,  0.1925],
        [-0.2156, -0.3077, -1.5949,  1.0177, -0.5163,  1.4049],
        [ 0.6170,  0.4535,  0.5172, -0.0322,  0.7324, -1.1831]])
------------------------------

tensor([ 0.0483, -0.4982, -0.6452])
tensor([-1.1533, -0.6372,  0.5783])
tensor([[ 0.0483, -0.4982, -0.645

## 3. 텐서의 연산

#### (1) 더하기, 빼기 연산

In [ ]:
import torch

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
print("tensor1 :", tensor1)
print("tensor2 :", tensor2)
print('')

# 덧셈
tensor3 = tensor1 + tensor2
print("tensor1 + tensor2 =", tensor3)

# 뺄셈
tensor4 = tensor1 - tensor2
print("tensor1 - tensor2 =", tensor4)

tensor1 : tensor([1, 2, 3])
tensor2 : tensor([4, 5, 6])

tensor1 + tensor2 = tensor([5, 7, 9])
tensor1 - tensor2 = tensor([-3, -3, -3])


#### (2) 곱하기 연산

In [ ]:
import torch

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
print("tensor1 :", tensor1)
print("tensor2 :", tensor2)
print('')

# 원소별 곱셈
tensor3 = tensor1 * tensor2
print("tensor1 * tensor2 =", tensor3)

tensor1 : tensor([1, 2, 3])
tensor2 : tensor([4, 5, 6])

tensor1 * tensor2 = tensor([ 4, 10, 18])


In [ ]:
import torch

tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Size: (2, 3)
tensor2 = torch.tensor([[7, 8], [9, 10], [11, 12]])  # Size: (3, 2)
print("tensor1 :\n", tensor1)
print("tensor1 size : ", tensor1.shape)
print("")
print("tensor2 :\n", tensor2)
print("tensor2 size : ", tensor2.shape)
print("")

# 행렬 곱셈
tensor3 = torch.matmul(tensor1, tensor2)
print("tensor1.matmul(tensor2) =\n", tensor3)
print("tensor1.matmul(tensor2) size = ", tensor3.shape)

tensor4 = torch.matmul(tensor2, tensor1)
print("tensor2.matmul(tensor1) =\n", tensor4)
print("tensor2.matmul(tensor1) size = ", tensor4.shape)

tensor1 :
 tensor([[1, 2, 3],
        [4, 5, 6]])
tensor1 size :  torch.Size([2, 3])

tensor2 :
 tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor2 size :  torch.Size([3, 2])

tensor1.matmul(tensor2) =
 tensor([[ 58,  64],
        [139, 154]])
tensor1.matmul(tensor2) size =  torch.Size([2, 2])
tensor2.matmul(tensor1) =
 tensor([[ 39,  54,  69],
        [ 49,  68,  87],
        [ 59,  82, 105]])
tensor2.matmul(tensor1) size =  torch.Size([3, 3])


#### (3) 나누기 연산

In [ ]:
import torch

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
print("tensor1 :", tensor1)
print("tensor2 :", tensor2)
print("dtype of tensor1 :", tensor1.dtype)
print("dtype of tensor2 :", tensor2.dtype)
print('')

# 원소별 나눗셈
tensor3 = tensor1 / tensor2
print("tensor1 / tensor2 =", tensor3)

# 결과 텐서의 데이터 타입 확인
print("Data type of the result: ", tensor3.dtype)

tensor1 : tensor([1, 2, 3])
tensor2 : tensor([4, 5, 6])
dtype of tensor1 : torch.int64
dtype of tensor2 : torch.int64

tensor1 / tensor2 = tensor([0.2500, 0.4000, 0.5000])
Data type of the result:  torch.float32


### 2) 텐서(Tensor)의 축을 따른 연산

In [ ]:
import torch

# (3, 3) 크기의 텐서 생성
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                      dtype=torch.float)
print("Original tensor:\n", tensor)
print("dtype of Original tensor:\n", tensor.dtype)
print('')

# sum 연산 (axis=0)
sum0 = tensor.sum(dim=0)
print("Sum along the first axis (dim=0):\n", sum0)

# mean 연산 (axis=1)
mean1 = tensor.mean(dim=1)
print("Mean along the second axis (dim=1):\n", mean1)

# max 연산 (axis=0)
max0, _ = tensor.max(dim=0)
print("Max along the first axis (dim=0):\n", max0)

# min 연산 (axis=1)
min1, _ = tensor.min(dim=1)
print("Min along the second axis (dim=1):\n", min1)

### 텐서(Tensor)의 기타 연산

In [ ]:
import torch

tensor1 = torch.tensor([1, 2, 3])
print("tensor1 :", tensor1)
print('')

# 절대값
tensor2 = torch.abs(tensor1)
print("torch.abs(tensor1) =", tensor2)

# 제곱근
tensor3 = torch.sqrt(tensor1)
print("torch.sqrt(tensor1) =", tensor3)

# 자연로그
tensor4 = torch.log(tensor1)
print("torch.log(tensor1) =", tensor4)

# 지수
tensor5 = torch.exp(tensor1)
print("torch.exp(tensor1) =", tensor5)

tensor1 : tensor([1, 2, 3])

torch.abs(tensor1) = tensor([1, 2, 3])
torch.sqrt(tensor1) = tensor([1.0000, 1.4142, 1.7321])
torch.log(tensor1) = tensor([0.0000, 0.6931, 1.0986])
torch.exp(tensor1) = tensor([ 2.7183,  7.3891, 20.0855])


### 문제
1. 아래 텐서에서 가장 안쪽 차원을 따라 sum, mean, max, min 모두 계산해보시오.
2. 아래 텐서에서 두번째 차원을 따라 sum, mean, max, min 모두 계산해보시오.  
3. 아래 텐서에서 가장 바깥쪽 차원을 따라 sum, mean, max, min 모두 계산해보시오.

In [ ]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]],
                        [[7, 8, 9], [10, 11, 12]]])
tensor.shape

NameError: name 'torch' is not defined

In [ ]:
print(tensor.sum(dim=-1))
print(tensor.mean(dim=-1, dtype=torch.float))
print(tensor.max(dim=-1))
print(tensor.min(dim=-1))

print(tensor.sum(dim=1))
print(tensor.mean(dim=1, dtype=torch.float))
print(tensor.max(dim=1))
print(tensor.min(dim=1))

print(tensor.sum(dim=0))
print(tensor.mean(dim=0, dtype=torch.float))
print(tensor.max(dim=0))
print(tensor.min(dim=0))

In [ ]:
print(tensor.mean(dim=-1, dtype=torch.float))
tensor.sum(dim=-1)/len(tensor[0, 0, :])